language: go
go:
  - "1.8"
  - "1.9"
  - "1.10"
  - master

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/require

script:
  - make cover
  - $GOPATH/bin/goveralls -service=travis-ci